/** Local order references and plain-text message/deep-link generation. */
import { isConfiguredTelegramUsername, isConfiguredWhatsAppNumber } from "@/config/contact";
import { DeliverySpeed, formatRupees, OrderTotals, ResolvedCartLine } from "@/lib/pricing";
export type OrderDetails = Readonly<{ name: string; topic: string; deadline: string; delivery: DeliverySpeed; notes: string }>;
export type OrderMessageInput = Readonly<{ orderId: string; lines: readonly ResolvedCartLine[]; totals: OrderTotals; details: OrderDetails }>;
const REFERENCE_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
export function createOrderReference(date = new Date(), random = Math.random): string { const datePart = [date.getFullYear(), date.getMonth() + 1, date.getDate()].map((value, index) => index === 0 ? String(value) : String(value).padStart(2, "0")).join(""); const suffix = Array.from({ length: 4 }, () => REFERENCE_ALPHABET[Math.min(REFERENCE_ALPHABET.length - 1, Math.floor(Math.max(0, random()) * REFERENCE_ALPHABET.length))]).join(""); return `SB-${datePart}-${suffix}`; }
export function formatOrderDeadline(value: string): string { const parsed = new Date(value); if (Number.isNaN(parsed.getTime())) return "To be confirmed"; return new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }).format(parsed); }
function deliveryMessageLabel(speed: DeliverySpeed, fee: number): string { return speed === "priority" ? `Priority delivery (+25%): ${formatRupees(fee)}` : speed === "same-day" ? `Same-day delivery (+50%): ${formatRupees(fee)}` : `Standard delivery: ${formatRupees(fee)}`; }
export function createOrderMessage({ orderId, lines, totals, details }: OrderMessageInput): string { const items = lines.map((line) => `${line.serviceName} — ${line.tierLabel}\n${formatRupees(line.unitPrice)} × ${line.quantity} = ${formatRupees(line.lineTotal)}`).join("\n\n"); return ["Hi Page & Slide,", "I'd like to place an order.", `Order: ${orderId}`, "ITEMS", items, `Subtotal: ${formatRupees(totals.subtotal)}`, deliveryMessageLabel(totals.validDelivery, totals.deliveryFee), `Total: ${formatRupees(totals.total)}`, `Name: ${details.name.trim()}`, `Topic / Requirement: ${details.topic.trim()}`, `Deadline: ${formatOrderDeadline(details.deadline)}`, `Notes:\n${details.notes.trim() || "None"}`, "Please confirm availability and the final order details."].join("\n\n"); }
export function createWhatsAppOrderUrl(number: string, message: string): string | null { return isConfiguredWhatsAppNumber(number) ? `https://wa.me/${number}?text=${encodeURIComponent(message)}` : null; }
export function createTelegramOrderUrl(username: string, message: string): string | null { return isConfiguredTelegramUsername(username) ? `https://t.me/${username}?text=${encodeURIComponent(message)}` : null; }
