import { StorefrontLayout } from "@/components/StorefrontLayout";
import { LEGAL_CONTACT_EMAIL } from "@/config/site";
import { LegalSection } from "@/data/legal";
import { ArrowLeft } from "lucide-react";

export function LegalPage({ title, intro, sections }: Readonly<{ title: string; intro: string; sections: readonly LegalSection[] }>) {
  return <StorefrontLayout><main><section className="legal-hero" aria-labelledby="legal-title"><a className="back-link detail-back" href="/"><ArrowLeft size={16} aria-hidden="true" /> Back to SoftBazzar</a><p className="eyebrow">CUSTOMER INFORMATION</p><h1 id="legal-title">{title}</h1><p>{intro}</p><p className="legal-updated">Plain-English policy · Review before placing an order</p></section><article className="legal-content">{sections.map((section) => <section className="legal-section" key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}{LEGAL_CONTACT_EMAIL ? <p className="legal-contact-email">Verified support and privacy contact: <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a></p> : <p className="legal-contact-email">A verified support and privacy email will be published before final production configuration. Until then, use the WhatsApp or Telegram links in the footer.</p>}</article></main></StorefrontLayout>;
}

export function ContactPage() {
  return <StorefrontLayout><main><section className="legal-hero contact-hero" aria-labelledby="contact-title"><a className="back-link detail-back" href="/"><ArrowLeft size={16} aria-hidden="true" /> Back to SoftBazzar</a><p className="eyebrow">DIRECT SUPPORT</p><h1 id="contact-title">Contact SoftBazzar.</h1><p>Choose a channel, share the order reference when you have one, and include the service, deadline, issue and outcome you are requesting.</p><div className="contact-actions"><a className="primary-action" href="https://wa.me/919025857269" target="_blank" rel="noopener noreferrer">Open WhatsApp</a><a className="secondary-action" href="https://t.me/softbazzar" target="_blank" rel="noopener noreferrer">Open Telegram</a></div></section><section className="contact-grid"><div><p className="eyebrow">ORDER SUPPORT</p><h2>What to include</h2><p>Include your order reference, the selected service, the confirmed deadline, a short description of the issue and the remedy you are requesting. Do not send passwords, payment-card details or unnecessary sensitive information.</p></div><div><p className="eyebrow">GRIEVANCE ROUTE</p><h2>What happens next</h2><p>SoftBazzar will acknowledge the request through the channel used, check the order details and explain the next step. If work has been delivered, attach only the relevant description or file context needed to review the issue.</p></div><div><p className="eyebrow">EMAIL CONFIGURATION</p><h2>No invented inbox.</h2><p>{LEGAL_CONTACT_EMAIL ? <>The verified support route is <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>.</> : "A support or privacy email has not yet been supplied, so none is displayed as if it were real. Use WhatsApp or Telegram until the verified address is configured."}</p></div></section></main></StorefrontLayout>;
}
