import { StorefrontLayout } from "@/components/StorefrontLayout";
import { createTelegramContactUrl, createWhatsAppContactUrl, TELEGRAM_USERNAME, WHATSAPP_NUMBER } from "@/config/contact";
import { LEGAL_CONTACT_EMAIL } from "@/config/site";
import { LegalSection } from "@/data/legal";
import { ArrowLeft } from "lucide-react";

const whatsappUrl = createWhatsAppContactUrl(WHATSAPP_NUMBER);
const telegramUrl = createTelegramContactUrl(TELEGRAM_USERNAME);

export function LegalPage({ title, intro, sections }: Readonly<{ title: string; intro: string; sections: readonly LegalSection[] }>) {
  return <StorefrontLayout><main><section className="legal-hero" aria-labelledby="legal-title"><a className="back-link detail-back" href="/"><ArrowLeft size={16} aria-hidden="true" /> Back to Page & Slide</a><p className="eyebrow">CUSTOMER INFORMATION</p><h1 id="legal-title">{title}</h1><p>{intro}</p><p className="legal-updated">Plain-English policy · Review before placing an order</p></section><article className="legal-content">{sections.map((section) => <section className="legal-section" key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}{LEGAL_CONTACT_EMAIL ? <p className="legal-contact-email">Support and privacy contact: <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a></p> : <p className="legal-contact-email">For support or privacy requests, use the configured contact channel in the footer.</p>}</article></main></StorefrontLayout>;
}

export function ContactPage() {
  return <StorefrontLayout><main><section className="legal-hero contact-hero" aria-labelledby="contact-title"><a className="back-link detail-back" href="/"><ArrowLeft size={16} aria-hidden="true" /> Back to Page & Slide</a><p className="eyebrow">DIRECT SUPPORT</p><h1 id="contact-title">Contact Page & Slide.</h1><p>Choose an available channel, share the order reference when you have one, and include the service, deadline, issue and outcome you are requesting.</p><div className="contact-actions">{whatsappUrl && <a className="primary-action" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Open WhatsApp</a>}{telegramUrl && <a className="secondary-action" href={telegramUrl} target="_blank" rel="noopener noreferrer">Open Telegram</a>}</div></section><section className="contact-grid"><div><p className="eyebrow">ORDER SUPPORT</p><h2>What to include</h2><p>Include your order reference, the selected service, the confirmed deadline, a short description of the issue and the remedy you are requesting. Do not send passwords, payment-card details or unnecessary sensitive information.</p></div><div><p className="eyebrow">GRIEVANCE ROUTE</p><h2>What happens next</h2><p>Page & Slide will acknowledge the request through the channel used, check the order details and explain the next step. If work has been delivered, attach only the relevant description or file context needed to review the issue.</p></div><div><p className="eyebrow">CONTACT CONFIGURATION</p><h2>Published routes only.</h2><p>{LEGAL_CONTACT_EMAIL ? <>The published email route is <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>.</> : "No support or privacy email is currently published. Use the configured WhatsApp contact route shown above."}</p></div></section></main></StorefrontLayout>;
}
