/** College Press: a compact useReducer cart with only validated cart lines persisted. */
import { readStoredCart, writeStoredCart } from "@/lib/cart-storage";
import { CartItem } from "@/lib/pricing";
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useReducer } from "react";
type CartAction = { type: "add" | "increase" | "decrease" | "remove"; serviceId: string; tierId: string };
type CartContextValue = Readonly<{ items: readonly CartItem[]; itemCount: number; addItem: (serviceId: string, tierId: string) => void; increaseItem: (serviceId: string, tierId: string) => void; decreaseItem: (serviceId: string, tierId: string) => void; removeItem: (serviceId: string, tierId: string) => void }>;
const CartContext = createContext<CartContextValue | null>(null);
function sameLine(item: CartItem, serviceId: string, tierId: string): boolean { return item.serviceId === serviceId && item.tierId === tierId; }
export function cartReducer(items: readonly CartItem[], action: CartAction): readonly CartItem[] { if (action.type === "add" || action.type === "increase") { const found = items.some((item) => sameLine(item, action.serviceId, action.tierId)); return found ? items.map((item) => sameLine(item, action.serviceId, action.tierId) ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { serviceId: action.serviceId, tierId: action.tierId, quantity: 1 }]; } if (action.type === "decrease") return items.flatMap((item) => !sameLine(item, action.serviceId, action.tierId) ? [item] : item.quantity > 1 ? [{ ...item, quantity: item.quantity - 1 }] : []); return items.filter((item) => !sameLine(item, action.serviceId, action.tierId)); }
export function CartProvider({ children }: PropsWithChildren) { const [items, dispatch] = useReducer(cartReducer, undefined, readStoredCart); useEffect(() => { writeStoredCart(items); }, [items]); const value = useMemo<CartContextValue>(() => ({ items, itemCount: items.reduce((count, item) => count + item.quantity, 0), addItem: (serviceId, tierId) => dispatch({ type: "add", serviceId, tierId }), increaseItem: (serviceId, tierId) => dispatch({ type: "increase", serviceId, tierId }), decreaseItem: (serviceId, tierId) => dispatch({ type: "decrease", serviceId, tierId }), removeItem: (serviceId, tierId) => dispatch({ type: "remove", serviceId, tierId }) }), [items]); return <CartContext.Provider value={value}>{children}</CartContext.Provider>; }
export function useCart(): CartContextValue { const value = useContext(CartContext); if (!value) throw new Error("useCart must be used within CartProvider"); return value; }
